#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p2_collatz       # job name
#SBATCH -o p2_collatz.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p normal           # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

ibrun ./collatz_mpi 1699417
ibrun ./collatz_mpi 16994167
ibrun ./collatz_mpi 169941673

date
