#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p2_vectoradd     # job name
#SBATCH -o p2_vectoradd.%j  # name of the output and error file
#SBATCH -N 2                # total number of nodes requested
#SBATCH -n 2                # total number of tasks requested
#SBATCH -p normal           # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

ibrun ./vectoradd_mpi 20000000
ibrun ./vectoradd_mpi 200000000
ibrun ./vectoradd_mpi 2000000000

date
